import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";

import "./styles/bootstrap.min.css";
import "./styles/flaticon.css";
import "./styles/remixicon.css";
import "./styles/dark-mode.css";
import "swiper/css";
import "swiper/css/pagination";
import "react-accessible-accordion/dist/fancy-example.css";

import "./styles/style.css";
import "./styles/responsive.css";

import TosterProvider from "@/providers/TosterProvider";
import { getCurrentUser } from "@/actions/getCurrentUser";

export const metadata = {
	title: "Teor - Classified Ads & Directory Listing Next.js Template",
	description: "Generated by create next app",
	metadataBase: new URL("http://localhost:300"),
	icons: [
		{
			rel: "icon",
			type: "image/x-icon",
			sizes: "32x32",
			url: "/favicon.ico",
		},
		{
			rel: "icon",
			type: "image/x-icon",
			sizes: "16x16",
			url: "/favicon.ico",
		},
		{
			rel: "apple-touch-icon",
			sizes: "180x180",
			url: "/favicon.ico",
		},
	],
};

export default async function RootLayout({ children }) {
	const currentUser = await getCurrentUser();

	return (
		<html lang="en">
			<body suppressHydrationWarning={true}>
				<TosterProvider />
				<Navbar currentUser={currentUser} />
				{children}
				<Footer />
			</body>
		</html>
	);
}
